### ISSUE TITLE
publishing different notes in different path in vault

### ISSUE THREAD

**Issue by erfanbashar1q** [mixasite/obsidian-mixa#1]
is there any way to upload different notes from different folders inside the vault? because right now I can just upload the notes that are located in one folder by indicating to it in the setting of the plugin...

**Comment by mixasite** [comment]
Hey Erfan,

Right now the options are
* Do not specify anything for the `Site Folder` field, which will sync all your vault
* Specify `Site Folder` without checking `Publish Referenced Files`, which will just publish the files in the folder you specified
* Specify `Site Folder` and check `Publish Referenced Files`, which will publish the files in the folder and any file/image referenced by those files in the `Site Folder`.

We are planning to add support for allowing to specify multiple `Site Folders` soon. We just added it to our roadmap, feel free to vote on it, or let any other people who might need it know to vote too:
https://trello.com/b/UG0i4eJR/mixa-roadmap

Thanks,
Mixa Team
